export const recipes = [
  {
    id: 1,
    title: "Chicken Karahi",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400",
    time: "45 min",
    ingredients: ["1kg Chicken", "4 Tomatoes", "2 Green Chilies", "1 tbsp Ginger Garlic Paste", "Salt to taste"],
    steps: [
      "Heat oil in a pan and fry the chicken until golden.",
      "Add tomatoes and cook until soft.",
      "Add spices and ginger garlic paste, cook for 5 minutes.",
      "Add water, cover, and simmer for 20 minutes.",
      "Garnish with green chilies and serve hot.",
    ],
  },
  {
    id: 2,
    title: "Vegetable Biryani",
    image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=400",
    time: "60 min",
    ingredients: ["2 cups Rice", "Mixed Vegetables", "1 Onion", "Biryani Masala", "Yogurt"],
    steps: [
      "Soak rice for 30 minutes.",
      "Fry onions until golden brown.",
      "Add vegetables, yogurt, and biryani masala, cook for 10 minutes.",
      "Layer rice on top and cook on low heat for 20 minutes.",
      "Mix gently and serve.",
    ],
  },
  {
    id: 3,
    title: "Beef Nihari",
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    time: "3 hours",
    ingredients: ["1kg Beef Shank", "Nihari Masala", "4 tbsp Flour", "Ginger, sliced", "Fried Onions"],
    steps: [
      "Cook beef shank with nihari masala and water for 2.5 hours.",
      "Mix flour with water to make a slurry.",
      "Add slurry to thicken the gravy, cook 20 more minutes.",
      "Garnish with ginger and fried onions.",
      "Serve hot with naan.",
    ],
  },
  {
    id: 4,
    title: "Beef Pulao",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400",
    time: "50 min",
    ingredients: ["500g Beef", "2 cups Rice", "Whole Spices", "2 Onions", "Ghee"],
    steps: [
      "Fry onions in ghee until golden.",
      "Add beef and whole spices, cook until tender.",
      "Add soaked rice and beef stock.",
      "Cook on low heat until rice is done.",
      "Serve hot with raita.",
    ],
  },
  {
    id: 5,
    title: "Seekh Kebab",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
    time: "35 min",
    ingredients: ["500g Minced Meat", "1 Onion, grated", "Coriander Leaves", "Kebab Masala", "1 Egg"],
    steps: [
      "Mix mince with all spices, onion, and egg.",
      "Shape into skewer-like kebabs.",
      "Grill or pan-fry until fully cooked.",
      "Serve with mint chutney and naan.",
    ],
  },
  {
    id: 6,
    title: "Chapli Kebab",
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=400",
    time: "40 min",
    ingredients: ["500g Minced Beef", "Tomatoes, chopped", "Coriander Seeds", "Green Chilies", "2 Eggs"],
    steps: [
      "Mix mince with chopped tomatoes, spices, and eggs.",
      "Shape into flat, round patties.",
      "Shallow fry in oil until crispy and golden.",
      "Serve hot with naan and salad.",
    ],
  },
  {
    id: 7,
    title: "Daal Chawal",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
    time: "40 min",
    ingredients: ["1 cup Lentils", "1 cup Rice", "1 Onion", "2 Tomatoes", "Garlic & Cumin"],
    steps: [
      "Boil lentils until soft.",
      "Prepare tempering with garlic, cumin, and onions.",
      "Add tomatoes and mix into cooked lentils.",
      "Cook rice separately and serve together.",
    ],
  },
  {
    id: 8,
    title: "Aloo Keema",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400",
    time: "35 min",
    ingredients: ["500g Minced Meat", "3 Potatoes, cubed", "1 Onion", "Tomatoes", "Spices"],
    steps: [
      "Fry onions until soft, add mince and cook.",
      "Add tomatoes and spices, cook until oil separates.",
      "Add potatoes and a little water.",
      "Simmer until potatoes are soft. Serve with roti.",
    ],
  },
  {
    id: 9,
    title: "Chicken Tikka",
    image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=400",
    time: "40 min",
    ingredients: ["1kg Chicken pieces", "Yogurt", "Tikka Masala", "Lemon Juice", "Garlic Paste"],
    steps: [
      "Marinate chicken with yogurt, spices, and lemon juice for 30 minutes.",
      "Skewer the chicken pieces.",
      "Grill or bake until charred and cooked through.",
      "Serve with mint chutney.",
    ],
  },
  {
    id: 10,
    title: "Sindhi Biryani",
    image: "https://images.unsplash.com/photo-1642821373181-696a54913e93?w=400",
    time: "70 min",
    ingredients: ["1kg Chicken", "3 cups Rice", "Potatoes", "Yogurt", "Biryani Masala"],
    steps: [
      "Cook chicken with yogurt, spices, and potatoes.",
      "Parboil rice separately.",
      "Layer chicken and rice alternately in a pot.",
      "Cook on low heat (dum) for 20 minutes and serve.",
    ],
  },
  {
    id: 11,
    title: "Chicken Handi",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    time: "45 min",
    ingredients: ["1kg Chicken", "Cream", "Tomato Paste", "Ginger Garlic Paste", "Green Chilies"],
    steps: [
      "Fry chicken with ginger garlic paste until golden.",
      "Add tomato paste and spices, cook until thick.",
      "Stir in cream and simmer for 10 minutes.",
      "Garnish with chilies and serve with naan.",
    ],
  },
  {
    id: 12,
    title: "Vegetable Curry",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400",
    time: "30 min",
    ingredients: ["Mixed Vegetables", "1 Onion", "2 Tomatoes", "Ginger Garlic Paste", "Curry Spices"],
    steps: [
      "Saute onions until translucent.",
      "Add tomatoes and spices, cook until soft.",
      "Add vegetables and a little water.",
      "Cover and simmer until vegetables are tender.",
    ],
  },
  {
    id: 13,
    title: "Fish Curry",
    image: "https://images.unsplash.com/photo-1626200419199-391ae4be7a41?w=400",
    time: "35 min",
    ingredients: ["500g Fish fillets", "Tamarind Paste", "Curry Leaves", "Coconut Milk", "Spices"],
    steps: [
      "Marinate fish with turmeric and salt.",
      "Prepare curry base with spices and coconut milk.",
      "Add fish gently and simmer until cooked.",
      "Garnish with curry leaves and serve with rice.",
    ],
  },
];